# Generated by Django 2.2.2 on 2019-06-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20190617_1922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('original', 'translation')},
        ),
    ]
